# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b8713b5e36a215e20f5ca4e8f693cf698529468860fb280746f7632e148237cc9e7bce4d9f180f5e1b2ac74eabefeee88e982365bc0bacb9b3dba96d2afaf80

test:
  secret_key_base: c47f3d84a1c06703861a498684c32f23da62d107a26a8772ff25fe90a36022662fd1446b6a787775b2808194d530ac913e2e292f6374f363e54cf91adc4f4c85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
